title: Eric C. Nordstrom
logo: /assets/img/e_nordstrom.jpg
description: Strategic Leader & Writer | Data-Driven Decision Maker | Transforming Content & Customer Experience with 15+ Years in Tech & Analytics
show_downloads: true
theme: jekyll-theme-minimal
